CREATE DATABASE DB_SISTEMA_VENTA
GO
USE DB_SISTEMA_VENTA
GO

CREATE TABLE ROL(
IdRol INT PRIMARY KEY IDENTITY,
Descripcion VARCHAR(255),
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO

CREATE TABLE PERMISO(
IdPermiso INT PRIMARY KEY IDENTITY,
IdRol INT REFERENCES ROL(IdRol),
NombreMenu VARCHAR(255),
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO

CREATE TABLE PROVEEDOR(
IdProveedor INT PRIMARY KEY IDENTITY,
Documento VARCHAR(255),
RazonSocial VARCHAR(255),
Correo VARCHAR(255),
Telefono VARCHAR(255),
Estado BIT, --ONLY STORES 1 OR 0
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO

CREATE TABLE CLIENTE(
IdCliente INT PRIMARY KEY IDENTITY,
Documento VARCHAR(255),
NombreCompleto VARCHAR(255),
Correo VARCHAR(255),
Telefono VARCHAR(255),
Estado BIT, --ONLY STORES 1 OR 0
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO

CREATE TABLE USUARIO(
IdUsuario INT PRIMARY KEY IDENTITY,
Documento VARCHAR(255),
NombreCompleto VARCHAR(255),
Correo VARCHAR(255),
Clave VARCHAR(255),
IdRol INT REFERENCES ROL(IdRol),
Estado BIT, --ONLY STORES 1 OR 0
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO


CREATE TABLE COMPRA(
IdCompra INT PRIMARY KEY IDENTITY,
IdUsuario INT REFERENCES USUARIO(IdUsuario),
IdProveedor INT REFERENCES PROVEEDOR(IdProveedor),
TipoDocumento VARCHAR(255),
NumeroDocumento VARCHAR(255),
MontoTotal DECIMAL(10,2),
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO

CREATE TABLE CATEGORIA(
IdCategoria INT PRIMARY KEY IDENTITY,
Descripcion VARCHAR(255),
Estado BIT, --ONLY STORES 1 OR 0
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO

CREATE TABLE PRODUCTO(
IdProducto INT PRIMARY KEY IDENTITY,
IdCategoria INT REFERENCES CATEGORIA(IdCategoria),
Codigo VARCHAR(255),
Nombre VARCHAR(255),
Descripcion VARCHAR(255),
Stock INT NOT NULL DEFAULT 0,
PrecioCompra DECIMAL(10,2) DEFAULT 0,
PrecioVenta DECIMAL(10,2) DEFAULT 0,
Estado BIT, --ONLY STORES 1 OR 0
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO

CREATE TABLE DETALLE_COMPRA(
IdDetalleCompra INT PRIMARY KEY IDENTITY,
IdCompra INT REFERENCES COMPRA(IdCompra),
IdProducto INT REFERENCES PRODUCTO(IdProducto),
PrecioCompra DECIMAL(10,2) DEFAULT 0,
PrecioVenta DECIMAL(10,2) DEFAULT 0,
Cantidad INT,
Total DECIMAL(10,2),
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO

CREATE TABLE VENTA(
IdVenta INT PRIMARY KEY IDENTITY,
IdUsuario INT REFERENCES USUARIO(IdUsuario),
TipoDocumento VARCHAR(255),
NumeroDocumento VARCHAR(255),
DocumentoCliente VARCHAR(255),
NombreCliente VARCHAR(255),
MontoPago DECIMAL(10,2),
MontoCambio DECIMAL(10,2),
MontoTotal DECIMAL(10,2),
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO

CREATE TABLE DETALLE_VENTA(
IdDetalleVenta INT PRIMARY KEY IDENTITY,
IdVenta INT REFERENCES VENTA(IdVenta),
IdProducto INT REFERENCES PRODUCTO(IdProducto),
PrecioVenta DECIMAL(10,2),
Cantidad INT,
SubTotal DECIMAL(10,2),
FechaRegistro DATETIME DEFAULT GETDATE()
)
GO